### ISSUE TITLE
Default behavior crashes anything that adds potions

### ISSUE THREAD

**Issue by falkreon** [Meldexun/CrystalicVoid#1]
**Expected behavior:** Any option that would crash other mods defaults to off

**Observed behavior:** Not only does this mod crash Extra Utilities, but it also aggressively crashes Ars Magica 2 and any other mod that adds potion recipes. Additionally, enabling stacking potions causes the vanilla brewing stand to delete potions after a brewing operation. This is why it's a crash.

**Known workarounds:** Unfortunately, Crystallic Void is unable to create a default config file during such a crash, but creating a new config file with stackablePotions disabled seems to clear the issue up.

**Comment by Meldexun** [comment]
Hi there, saw this problem some days before. I will try that Potions are stackable and still the rest works, but this will take some time.

**Comment by falkreon** [comment]
Making potions stackable is bad.
It deletes potions in the brewing stand.
Forge is trying to warn you about the problem.
If potions are stackable, it will crash.

The best resolution to the problem is to default this to "off".

**Comment by Meldexun** [comment]
So I'm back now and i set it's default to off. (can be activated in config)
