### ISSUE TITLE
Config doesn't apply changes in game.

### ISSUE THREAD

**Issue by BlueJayBlaze** [Meldexun/CrystalicVoid#2]
Firstly, I'd just like to say I love your mod and I like all the adjustments, especially the config.
However as the title suggests I am having issues using the config.
I play Minecraft version 1.11.2.
I tried using Notepad++ but a whole bunch of labels appeared in the place of values.
So instead I used dirtyjoe and it worked better.
But everytime I try to change a armor or tool durability, it doesn't work in game.
I saved my work, overwrote the config in the .jar with it, and still it does nothing.
Hope to hear from you, I just want to be able to change the durability to make the armor less overpowered, among possible other changes like the potion effects.
Thank you.

**Comment by Meldexun** [comment]
Hey there,
i think you edited not the right config. The config files are normally in this folder:
C:\Users\\"yourName"\AppData\Roaming\\.minecraft\config
There is a "CrystalicVoid.cfg" file. You should be able to edit that file with the normal notepad.

**Comment by BlueJayBlaze** [comment]
Thank you so much! I had no clue about the config folder and files actually. :P 
Also thanks for responding so quickly!
