### ISSUE TITLE
Crash on world loading

### ISSUE THREAD

**Issue by Iashar** [Meldexun/CrystalicVoid#4]
Not sure what happens to cause this, or what I possibly did wrong.

MC 1.12.2
forge 14.23.4.2759
Meldexun'sCrystalicVoid-1.12.2-2.4.104

Crash report:
https://pastebin.com/F1beNsL0

**Comment by Meldexun** [comment]
I saw that issue too. Already fixed it in version 2.4.105. Still thank you for reporting the issue.
